#!/usr/bin/env bash

if [ ! -e .env ]; then
    cp .env.dist .env
fi

if [ "$1" == "up" ]; then
     if [ ! -f docker/php/var/.ssh/id_rsa ]; then
         cp ~/.ssh/* docker/php/var/.ssh/
     fi
     docker-compose "$@"
elif [ "$1" == "enter-root" ]; then
    docker-compose exec -u root php bash
elif [ "$1" == "enter" ]; then
    docker-compose exec -u user php bash
elif [ $# -gt 0 ]; then
    docker-compose "$@"
else
    docker-compose ps
fi
