version: '3'

volumes:
  db_volume: {}
  composer_volume: {}
  log_volume: {}
  history_volume: {}

services:

  php:
    build: docker/php
    tty: true # -t option in docker
    stdin_open: true # -i option in docker
    hostname: ${HOSTNAME}
    volumes:
      - ./:/var/www/project
      - composer_volume:/home/user/.composer
      - history_volume:/home/user/history
    env_file:
      - .env
    extra_hosts:
      - "www.example.com:192.168.0.1"

  web:
    image: nginx:latest
    ports:
      - '${LOCALHOST}:80:80'
    depends_on:
      - php
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/symfony-4.conf:/etc/nginx/conf.d/default.conf
      - log_volume:/var/log/nginx
      #- ./docker/nginx/nginx.conf:/etc/nginx/s.conf

  db:
    image: mysql:5.7
    restart: always
    command: mysqld --sql_mode=""
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${LOCALHOST}:3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${LOCALHOST}:81:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
